Commit R package
mrc-ide/mockcpp pull request #1
Opened 2020-10-19 16:04 UTC by giovannic

2020-10-20 12:05 UTC, richfitz requested changes
Some thoughts on structure and setup; feel free to object and/or park in other tickets :)

2020-10-20 12:05 UTC, richfitz commented on DESCRIPTION
> +  Rcpp,
Is there any scope to make this agnostic as to the interface library?

2020-10-20 12:05 UTC, richfitz commented on README.md
>  For basic examples, please refer to: `src/test-mocking.cpp`
on line 7 the link has brackets/parens the wrong way so the link does not render

2020-10-20 12:05 UTC, richfitz commented on inst/include/trompeloeil.hpp
> +/*
I feel we should be shipping a full copy of the licence for this, and the copyright information should be reflected into the DESCRIPTION. If this will ever go on CRAN they're very picky (and yet inconsistent) about how these people should be credited, but using "cph" for now seems a good start

2020-10-20 12:05 UTC, richfitz commented on inst/include/trompeloeil.hpp
> +#include <Rcpp.h>
This looks like you have a modified copy of the upstream library. I usually manage this by a script that patches the upstream library with the wanted modification so that I can track upstream changes. It would be good to know what version this is using too

2020-10-20 12:05 UTC, richfitz commented on inst/include/trompeloeil.hpp
> +      Rcpp::stop("Should not be called"); // must never be called
if this is the only Rcpp-provided feature, it should be possible to make this work with cpp11 too; I can look into that if you're interested (in a subsequent PR)

2020-10-20 12:05 UTC, richfitz commented on inst/include/testthat/trompeloeil.hpp
> +#error "<testthat.h> must be included before <testthat/trompeloeil.hpp>"
Can you not do the include yourself here?

2020-10-20 12:05 UTC, richfitz commented on inst/include/testthat/trompeloeil.hpp
> +/*
should your path here be `inst/include/mockcpp/trompeloeil.hpp`?

2020-10-20 12:05 UTC, richfitz commented on inst/include/mockcpp.h
> +#include "testthat/trompeloeil.hpp"
Should this be angle brackets? I never know as both seem to work quite often

2020-10-20 16:23 UTC, giovannic commented on README.md
>  For basic examples, please refer to: `src/test-mocking.cpp`
thanks, fixed in master

2020-10-21 17:11 UTC, giovannic commented on inst/include/mockcpp.h
> +#include "testthat/trompeloeil.hpp"
I have always thought " can be used for anything relative to the source path and < has to be used for things in the system path.

I've tested this in the individual package and it works :)

2020-10-21 17:42 UTC, giovannic commented on inst/include/trompeloeil.hpp
> +/*
The R package check throws a warning if the license is not called "LICENCE/LICENSE". It only seems to allow one full license to ship? I've skipped it for now.

But I've added the trompeloeil cph 👍

2020-10-21 17:42 UTC, giovannic commented
Thanks for that! I've removed Rcpp, the original code and updated the licensing

2020-10-22 07:11 UTC, richfitz commented on inst/include/trompeloeil.hpp
> +/*
What I did in thor (https://github.com/richfitz/thor), which does a similar mixed licencing thing, is:

* At the bottom of the README in the licence section wrote "MIT + file LICENSE © Rich FitzJohn. The package contains included code from lmdb which it itself under the "OpenLDAP Public License" - see inst/LICENSE.lmdb for details" (this was a personal project)
* Included a full copy of the OpenLDAP licence in the package at inst/LICENSE.lmdb (https://github.com/richfitz/thor/blob/master/inst/LICENSE.lmdb)

CRAN seemed relaxed about that. The BPL seems very similar to the MIT so this mix should be fine

2020-10-22 07:22 UTC, richfitz requested changes
It would be good to get tests that use this package in other demo packages - these will be fiddly to write and involve adding a ton of things to the Suggests - probably worth doing in a second PR.

I can't install this package on ubuntu:

```
* installing to library ‘/home/rfitzjoh/lib/R/library’
* installing *source* package ‘mockcpp’ ...
** using staged installation
** libs
g++ -std=gnu++14 -I"/usr/share/R/include" -DNDEBUG  -I'/home/rfitzjoh/lib/R/library/testthat/include' -g -Wall -Wextra -pedantic -Wmaybe-uninitialized -Wno-unused-parameter -Wno-unused-variable -O2   -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-8T8CYO/r-base-4.0.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c test-mocking.cpp -o test-mocking.o
In file included from test-mocking.cpp:2:
../inst/include/mockcpp.h:1:10: fatal error: testthat/trompeloeil.hpp: No such file or directory
    1 | #include "testthat/trompeloeil.hpp"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [/usr/lib/R/etc/Makeconf:181: test-mocking.o] Error 1
ERROR: compilation failed for package ‘mockcpp’
* removing ‘/home/rfitzjoh/lib/R/library/mockcpp’
```

Can you run `make` and commit the result so that the generated files are included, otherwise installing this package will require cloning the git repo and a fairly manual install, which will make it hard to use from other projects.

2020-10-22 07:22 UTC, richfitz commented on README.md
> +This R package is licenced under MIT but is mostly made of the Boost licensed
Above in the README example you can remove Rcpp from the package list now.

2020-10-22 10:12 UTC, richfitz approved these changes

2020-10-22 10:12 UTC, merged